# Generated by Django 5.2 on 2025-09-24 20:02

import django.db.models.deletion
import orange.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, default="")),
                ("description_short", models.TextField(blank=True, default="")),
                ("additional_info", models.TextField(blank=True, default="")),
                (
                    "mainpic",
                    models.ImageField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        upload_to="antonspro/css/orange/eventpics",
                    ),
                ),
                ("price", models.TextField(blank=True, default="")),
                ("link_to_external_site", models.TextField(blank=True, default="")),
                ("link_button_text", models.TextField(blank=True, default="")),
                (
                    "tendies",
                    models.ManyToManyField(
                        blank=True, related_name="tendies", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventowner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("closed", models.BooleanField(default=False)),
                ("times", models.JSONField(default=orange.models.Day.day_default)),
                ("events", models.ManyToManyField(blank=True, to="orange.event")),
            ],
            options={"ordering": ["date"],},
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "mainpic",
                    models.ImageField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        upload_to="antonspro/css/orange/clubpics",
                    ),
                ),
                ("link_to_external_site", models.TextField(blank=True, default="")),
                ("link_button_text", models.TextField(blank=True, default="")),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="org_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="org_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="org_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "president",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_president",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orange.organization",
            ),
        ),
    ]
