# Generated by Django 5.2 on 2025-09-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orange", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="mainpic",
            field=models.ImageField(
                blank=True, max_length=1000, null=True, upload_to="orange/css/eventpics"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="mainpic",
            field=models.ImageField(
                blank=True, max_length=1000, null=True, upload_to="orange/css/clubpics"
            ),
        ),
    ]
