# Generated by Django 3.1.2 on 2021-06-28 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bitcoin', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Bitcoin')),
                ('Ethereum', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Ethereum')),
                ('Dogecoin', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Dogecoin')),
                ('Ripple', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Ripple')),
                ('EOS', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='EOS')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('gold', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='gold')),
                ('cryptos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coins')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
