# Generated by Django 3.1.2 on 2021-06-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210628_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cryptos',
        ),
        migrations.DeleteModel(
            name='Coins',
        ),
    ]
