# Generated by Django 3.1.2 on 2021-07-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210629_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='gold'),
        ),
    ]
