# Generated by Django 3.1.2 on 2021-12-11 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210702_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(related_name='_account_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
