# Generated by Django 3.1.2 on 2021-12-30 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='friend_request',
            field=models.ManyToManyField(related_name='_account_friend_request_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
