# Generated by Django 3.1.2 on 2021-12-31 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_friend_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='friend_request',
            field=models.ManyToManyField(related_name='requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
