# Generated by Django 3.1.2 on 2022-01-02 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220102_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(related_name='_account_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
