# Generated by Django 3.1.2 on 2022-01-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220102_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='display_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/antonspro/css/Stream/pics'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_black',
            field=models.BooleanField(default=False),
        ),
    ]
