# Generated by Django 3.2.5 on 2023-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220114_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cardlist',
            field=models.FileField(blank=True, null=True, upload_to='cardtrader/userlists'),
        ),
    ]
