# Generated by Django 3.2.5 on 2023-12-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_cardlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cashapp',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='hascashapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='haspaypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='hasvenmo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='paypalname',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='venmoname',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
