# Generated by Django 3.2.5 on 2024-01-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20231221_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='countgiven',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='countgotten',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='scoregiven',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='account',
            name='scoregotten',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
