# Generated by Django 3.2.5 on 2024-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20240120_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
    ]
