# Generated by Django 3.2.5 on 2024-01-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='shippinginfo',
            field=models.TextField(default='None'),
        ),
    ]
