# Generated by Django 3.2.5 on 2024-02-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_account_shippinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='premium_amount',
            field=models.IntegerField(default=0),
        ),
    ]
