# Generated by Django 5.2 on 2025-09-01 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_account_premium_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="friends",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
