# Generated by Django 5.2 on 2025-09-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_account_friends"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="cardlist",),
        migrations.RemoveField(model_name="account", name="cashapp",),
        migrations.RemoveField(model_name="account", name="countgiven",),
        migrations.RemoveField(model_name="account", name="countgotten",),
        migrations.RemoveField(model_name="account", name="friend_request",),
        migrations.RemoveField(model_name="account", name="friends",),
        migrations.RemoveField(model_name="account", name="gold",),
        migrations.RemoveField(model_name="account", name="hascashapp",),
        migrations.RemoveField(model_name="account", name="haspaypal",),
        migrations.RemoveField(model_name="account", name="hasvenmo",),
        migrations.RemoveField(model_name="account", name="is_black",),
        migrations.RemoveField(model_name="account", name="paypalname",),
        migrations.RemoveField(model_name="account", name="premium_amount",),
        migrations.RemoveField(model_name="account", name="scoregiven",),
        migrations.RemoveField(model_name="account", name="scoregotten",),
        migrations.RemoveField(model_name="account", name="venmoname",),
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
