# Generated by Django 5.2 on 2025-09-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_remove_account_cardlist_remove_account_cashapp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="display_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/orange/userpics"
            ),
        ),
    ]
