# Generated by Django 5.2 on 2025-09-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_account_display_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="display_pic",
            field=models.ImageField(blank=True, null=True, upload_to="orange/userpics"),
        ),
    ]
