languagedic={
  "en":{
        "home":{
          "title1":"A place for meeting,",
          "title2":"discovery, and exchange",
          "homedescription":"The Thun Orangery is being revitalized as a non-commercial space for collaborative crafting, learning, and socializing. It combines a workshop, knowledge exchange, and a café into a meeting place open to everyone.",
          "program":"Program",
          "where":"Where you can find us",
          "create":"Create a profile to receive our Newsletter!",
          "getinfo":"Receive sporadic information about the Orangery Thun and find out about upcoming events.",
          "assure":"Your email address will only be used to send you information about our activities. You can unsubscribe at any time using the unsubscribe link in our emails.",
          "createaccount":"Create Account",
          "follow":"Follow us!",
          "write":"Write us :)",
          "oclock":"o'clock",
          "host":"Hosted by: ",
          "more":"More Info"
        },
        "event_info":{
            "price":"Price: ",
            "num":"Number of Attendies:",
            "youare":"You are Attending, cant make it? no problem.",
            "let":"Let",
            "know":"know your coming, and get updates via Email",
            "cancel":"Cancel attendance",
            "join":"Join Event!"
        },
        "calander":{
          "available":"Free",
          "event":"Event",
          "guide":"How-To Guide",
          "addevent":"Add Event",
          "addeventnot":"Sign in to Post Events!",
          "sun":"Sun",
          "mon":"Mon",
          "tue":"Tue",
          "wed":"Wed",
          "thu":"Thu",
          "fri":"Fri",
          "sat":"Sat",
          "choose":"Choose an Event",
          "createnew":"Create New",
          "savechanges":"Save Changes",
          "timefree":"O'clock Free",
          "guide1":"Step one: Create an Event",
          "guide2":"You will See this Button all throughout this website, it brings up the event form.",
          "guide3":"On the Event Form, only the first four lines are required.",
          "guide4":"The Events name",
          "guide5":"Short description ( this appears on the websites homepage, keep breif! )",
          "guide6":"Full descritpiton, this only appears on the events personal page",
          "guide7":"Additional Info, also only on the event page. example: contact info, dress requirements etc...",
          "guide8":"this lets visitors know WHO is hosting this Event, when blank, its you.",
          "guide9":"Price. If blank, its will be set to free.",
          "guide10":"You can Have an image as well, but its only viewable from the Events Personal Page.",
          "guide11":"If your event has an external website, you can link it! Eventfrog,facebook,instagram etc...",
          "guide12":"if you added a link, tell the person where it goes here!",
          "guide13":"Next Page",
          "guide14":"Step Two: Choose the date and Time.",
          "guide15":"Simply click on an upcoming day on the calander ( you can also move to another month if needed. )",
          "guide16":"Next, Choose the Event you want to post from the top bar.",
          "guide17":"Then click all the times that the event will go on for, from the start, all the way to the end. ( upon clicking the time will change color )",
          "guide18":"When your done, click the save button. And boom! all done!",
          "guide19":"Now when your event is amoung the next 10 events being held at the Orangerie, it will appear on the homepage!",
          "guide20":"O'clock",
        },
        "nav":{
            "logout":"log out",
            "signup":"Sign up",
            "forgot":"FORGOT?",
            "login":"Log in",
            "goal":"Goal / About Us",
            "contact":"Contact",
            "ecal":"Event Calander",
            "password":"Password",
        },
        "event_form":{
            "name":"Event Name",
            "des":"Short Description",
            "full":"Full Description of Event",
            "add":"Additional Info (keep short)",
            "host":"Host Organization",
            "price":"price ( free by default )",
            "linkto":"link to external site ( optional )",
            "linkdes":"description of where link goes",
            "post":"Post Event"
        },
        "org_info":{
            "member":"Your a Member of",
            "join":"Want to become a member?",
            "joinit":"Request to Join"
        },
        "profile":{
            "pro":"profile",
            "org":"Organizations",
            "eve":"Event Manager",
            "email":"Send Emails",
            "upload":"Upload Profile Pic",
            "del":"Delete Profile Pic",
            "save":"Save changes",
            "noorg":"Is not a part of any Organizations",
            "crenew":"Create New Organization",
            "memof":"You are a Member of:",
            "leave":"Leave",
            "request":"Requests to join",
            "app":"Approve",
            "dec":"Decline",
            "nonew":"There are no new requests.",
            "presof":"You are the president of",
            "makead":"Make Admin",
            "kick":"Remove from Club",
            "demote":"Demote",
            "visitclub":"Visit Clubs Page",
            "addev":"Add Event",
            "edit":"Edit",
            "delete":"Delete",
            "nameof":"Name of Organization",
            "orgdes":"Description of your Organization",
            "disimg":"Display image",
            "orglink":"Link to Organizations Website ( optional )",
            "orgwhere":"Where does the link Lead? ( optional )",
            "youpres":"Are you the President?",
            "yes":"yes",
            "no":"no",
            "sub":"Submit",
            "confirm":"Confirm",
            "cancel":"Cancel",
            "maillist":"Select Mailing list",
            "alllist":"Every User",
            "emailmess":"Email Body",
            "sendemails":"Send Email(s)",
            "emailsub":"Email Subject",
            "emailhead":"Email Header",
        },
        "alert":{
            "nouser1":"No user exists with the email ",
            "nouser2":". Try signing up with that email instead, or check for mis-spellings",
            "nopass":"Wrong Password for ",
            "taken1":"A User with the Email adress ",
            "taken2":" is already in use.",
            "eve1":"Event Created Succesfully",
            "eve2":"An Event With that name already Exisits, no duplicates allowed!"
        },
        "about":{},
        "goal":{}
    },
  "de":{
        "home":{
          "title1":"Ort für gemeinsames Treffen,",
          "title2":"Entdecken und Austauschen",
          "homedescription":"Die Orangerie Thun wird als nicht-kommerzieller Raum für gemeinsames Handwerken, Lernen und Begegnen wiederbelebt. Sie verbindet Werkstatt, Wissensaustausch und Café zu einem offenen Treffpunkt für alle.",
          "program":"Programm",
          "where":"Wo wir zu finden sind:",
          "create":"Melde dich für unseren Newsletter an!",
          "getinfo":"Erhalte sporadisch Infos zur Orangerie Thun und informiere dich über kommende Veranstaltungen.",
          "assure":"Deine E-Mail-Adresse wird nur verwendet, um dir Informationen über unsere Aktivitäten zuzusenden. Du kannst dich jederzeit über den Abmeldelink in unseren E-Mails abmelden.",
          "createaccount":"Anmelden",
          "follow":"Folgen uns!",
          "write":"Schreib uns :)",
          "oclock":"uhr",
          "host":"veranstaltet von: ",
          "more":"Weitere Info"
        },
        "event_info":{
            "price":"Preis: ",
            "num":"Anzahl der Teilnehmer:",
            "youare":"Sie nehmen teil, können aber nicht kommen? Kein Problem.",
            "let":"Informieren Sie",
            "know":"über Ihr Kommen und erhalten Sie Updates per E-Mail",
            "cancel":"Teilnahme absagen",
            "join":"Nehmen Sie an der Veranstaltung teil!"
        },
        "calander":{
          "available":"verfügbar",
          "event":"Event",
          "guide":"Anleitung",
          "addevent":"Event hinzufügen",
          "addeventnot":"Melden Sie sich an, um Ereignisse zu veröffentlichen!",
          "sun":"Son",
          "mon":"Mon",
          "tue":"Din",
          "wed":"Mit",
          "thu":"Don",
          "fri":"Fri",
          "sat":"Sam",
          "choose":"Wählen Sie ein Event",
          "createnew":"Neu erstellen",
          "savechanges":"Änderungen speichern",
          "timefree":"uhr verfügbar",
            "guide1":"Schritt eins: Ein Ereignis erstellen",
            "guide2":"Sie werden diesen Button auf der gesamten Webseite sehen; er öffnet das Veranstaltungsformular.",
            "guide3":"Auf dem Veranstaltungsformular müssen nur die ersten vier Zeilen ausgefüllt werden.",
            "guide4":"Der Name des Ereignisses",
            "guide5":"Kurzbeschreibung (diese erscheint auf der Startseite der Website, bitte kurz fassen!)",
            "guide6":"Vollständige Beschreibung, diese wird nur auf der persönlichen Veranstaltungsseite angezeigt.",
            "guide7":"Weitere Informationen finden Sie ebenfalls nur auf der Veranstaltungsseite. Beispiele: Kontaktinformationen, Kleiderordnung usw.",
            "guide8":"Dadurch erfahren die Besucher, WER diese Veranstaltung ausrichtet; wenn leer, sind Sie es.",
            "guide9":"Preis. Falls leer, wird das Feld auf kostenlos gesetzt.",
            "guide10":"Sie können auch ein Bild hinzufügen, dieses ist jedoch nur auf der persönlichen Veranstaltungsseite sichtbar.",
            "guide11":"Wenn Ihre Veranstaltung eine externe Website hat, können Sie diese verlinken! Eventfrog, Facebook, Instagram usw.",
            "guide12":"Wenn Sie einen Link hinzugefügt haben, teilen Sie der Person hier mit, wohin er führt!",
            "guide13":"Nächste Seite",
            "guide14":"Zweiter Schritt: Datum und Uhrzeit auswählen.",
            "guide15":"Klicken Sie einfach auf einen der nächsten Tage im Kalender (bei Bedarf können Sie auch zu einem anderen Monat wechseln).",
            "guide16":"Wählen Sie anschließend in der oberen Leiste die Veranstaltung aus, die Sie veröffentlichen möchten.",
            "guide17":"Klicken Sie anschließend auf alle Zeiträume, die das Ereignis dauern soll, vom Beginn bis zum Ende. (Beim Klicken ändert sich die Farbe der Zeitangabe.)",
            "guide18":"Wenn du fertig bist, klicke auf den Speichern-Button. Und zack! Fertig!",
            "guide19":"Wenn Ihre Veranstaltung zu den nächsten 10 Veranstaltungen in der Orangerie gehört, wird sie auf der Startseite angezeigt!",
            "guide20":"Uhr",
        },
        "nav":{
            "logout":"abmelden",
            "signup":"Anmelden",
            "forgot":"vergessen?",
            "login":"Einloggen",
            "goal":"Ziel / Über uns",
            "contact":"Kontaktieren",
            "ecal":"Veranstaltungskalender",
            "password":"Passwort",
        },
        "event_form":{
            "name":"Event Name",
            "des":"Beschreibung",
            "full":"Vollständige Beschreibung der Veranstaltung",
            "add":"Zusätzliche Informationen (kurz halten)",
            "host":"Gastorganisation",
            "price":"Preis (standardmäßig kostenlos)",
            "linkto":"Link zu einer externen Site (optional)",
            "linkdes":"Beschreibung, wohin der Link führt",
            "post":"Post-Event"
        },
        "org_info":{
            "member":"Sie sind Mitglied von",
            "join":"Möchten Sie Mitglied werden?",
            "joinit":"Beitrittsanfrage"
        },
        "profile":{
            "pro":"Profil",
            "org":"Organisationen",
            "eve":"Eventmanager",
            "email":"Send Emails",
            "upload":"Profilbild hochladen",
            "del":"Profilbild löschen",
            "save":"Änderungen speichern",
            "noorg":"Ist kein Teil einer Organisation",
            "crenew":"Erstellen Sie eine neue Organisation",
            "memof":"Sie sind Mitglied von:",
            "leave":"Verlassen",
            "request":"Beitrittsanfragen",
            "app":"Genehmigen",
            "dec":"ablehnen",
            "nonew":"Es liegen keine neuen Anfragen vor.",
            "presof":"Sie sind der Präsident von",
            "makead":"Machen Sie Admin",
            "kick":"Aus dem Club entfernen",
            "demote":"Degradieren",
            "visitclub":"Besuchen Sie die Clubseite",
            "addev":"Event hinzufügen",
            "edit":"Bearbeiten",
            "delete":"Löschen",
            "nameof":"Name der Organisation",
            "orgdes":"Beschreibung Ihrer Organisation",
            "disimg":"Bild anzeigen",
            "orglink":"Link zur Website der Organisation (optional)",
            "orgwhere":"Wohin führt der Link? (optional)",
            "youpres":"Sind Sie der Präsident?",
            "yes":"ya",
            "no":"nein",
            "sub":"Absenden",
            "confirm":"Bestätigen",
            "cancel":"Abbrechen",
            "maillist":"Wählen Sie Mailingliste",
            "alllist":"Jeder Benutzer",
            "emailmess":"E-Mail-Text",
            "sendemails":"E-Mail(s) senden",
            "emailsub":"E-Mail-Betreff",
            "emailhead":"E-Mail-Header",
        },
        "about":{},
        "goal":{}
    }
 }
