languagedic={
  "en":{
        "home":{
          "title1":"A place for meeting,",
          "title2":"discovery, and exchange",
          "homedescription":"The Thun Orangery is being revitalized as a non-commercial space for collaborative crafting, learning, and socializing. It combines a workshop, knowledge exchange, and a café into a meeting place open to everyone.",
          "program":"Program",
          "where":"Where you can find us",
          "create":"Create a profile to receive our Newsletter!",
          "getinfo":"Receive sporadic information about the Orangery Thun and find out about upcoming events.",
          "assure":"Your email address will only be used to send you information about our activities. You can unsubscribe at any time using the unsubscribe link in our emails.",
          "createaccount":"Create Account",
          "follow":"Follow us!",
          "write":"Write us :)",
          "oclock":"o'clock",
          "host":"Hosted by: ",
          "more":"More Info"
        },
        "event_info":{
            "price":"Price: ",
            "num":"Number of Attendies:",
            "youare":"You are Attending, cant make it? no problem.",
            "let":"Let",
            "know":"know your coming, and get updates via Email",
            "cancel":"Cancel attendance",
            "join":"Join Event!"
        },
        "calander":{
          "available":"Free",
          "event":"Event",
          "addevent":"Add Event",
          "addeventnot":"Sign in to Post Events!",
          "sun":"Sun",
          "mon":"Mon",
          "tue":"Tue",
          "wed":"Wed",
          "thu":"Thu",
          "fri":"Fri",
          "sat":"Sam",
          "choose":"Choose an Event",
          "createnew":"Create New",
          "savechanges":"Save Changes",
          "timefree":"O'clock Free"
        },
        "nav":{
            "logout":"log out",
            "signup":"Sign up",
            "forgot":"FORGOT?",
            "login":"Log in",
            "goal":"Goal / About Us",
            "contact":"Contact",
            "ecal":"Event Calander",
            "password":"Password",
        },
        "event_form":{
            "name":"Event Name",
            "des":"Description",
            "add":"Additional Info (keep short)",
            "host":"Host Organization",
            "price":"price ( free by default )",
            "linkto":"link to external site ( optional )",
            "linkdes":"description of where link goes",
            "post":"Post Event"
        },
        "org_info":{
            "member":"Your a Member of",
            "join":"Want to become a member?",
            "joinit":"Request to Join"
        },
        "profile":{
            "pro":"profile",
            "org":"Organizations",
            "eve":"Event Manager",
            "email":"Send Emails",
            "upload":"Upload Profile Pic",
            "del":"Delete Profile Pic",
            "save":"Save changes",
            "noorg":"Is not a part of any Organizations",
            "crenew":"Create New Organization",
            "memof":"You are a Member of:",
            "leave":"Leave",
            "request":"Requests to join",
            "app":"Approve",
            "dec":"Decline",
            "nonew":"There are no new requests.",
            "presof":"You are the president of",
            "makead":"Make Admin",
            "kick":"Remove from Club",
            "demote":"Demote",
            "visitclub":"Visit Clubs Page",
            "addev":"Add Event",
            "edit":"Edit",
            "delete":"Delete",
            "nameof":"Name of Organization",
            "orgdes":"Description of your Organization",
            "disimg":"Display image",
            "orglink":"Link to Organizations Website ( optional )",
            "orgwhere":"Where does the link Lead? ( optional )",
            "youpres":"Are you the President?",
            "yes":"yes",
            "no":"no",
            "sub":"Submit",
            "confirm":"Confirm",
            "cancel":"Cancel",
            "maillist":"Select Mailing list",
            "alllist":"Every User",
            "emailmess":"Email Body",
            "sendemails":"Send Email(s)",
            "emailsub":"Email Subject",
            "emailhead":"Email Header",
        }
    },
  "de":{
        "home":{
          "title1":"Ort für gemeinsames Treffen,",
          "title2":"Entdecken und Austauschen",
          "homedescription":"Die Orangerie Thun wird als nicht-kommerzieller Raum für gemeinsames Handwerken, Lernen und Begegnen wiederbelebt. Sie verbindet Werkstatt, Wissensaustausch und Café zu einem offenen Treffpunkt für alle.",
          "program":"Programm",
          "where":"Wo wir zu finden sind:",
          "create":"Melde dich für unseren Newsletter an!",
          "getinfo":"Erhalte sporadisch Infos zur Orangerie Thun und informiere dich über kommende Veranstaltungen.",
          "assure":"Deine E-Mail-Adresse wird nur verwendet, um dir Informationen über unsere Aktivitäten zuzusenden. Du kannst dich jederzeit über den Abmeldelink in unseren E-Mails abmelden.",
          "createaccount":"Anmelden",
          "follow":"Folgen uns!",
          "write":"Schreib uns :)",
          "oclock":"uhr",
          "host":"veranstaltet von: ",
          "more":"Weitere Info"
        },
        "event_info":{
            "price":"Preis: ",
            "num":"Anzahl der Teilnehmer:",
            "youare":"Sie nehmen teil, können aber nicht kommen? Kein Problem.",
            "let":"Informieren Sie",
            "know":"über Ihr Kommen und erhalten Sie Updates per E-Mail",
            "cancel":"Teilnahme absagen",
            "join":"Nehmen Sie an der Veranstaltung teil!"
        },
        "calander":{
          "available":"verfügbar",
          "event":"Event",
          "addevent":"Event hinzufügen",
          "addeventnot":"Melden Sie sich an, um Ereignisse zu veröffentlichen!",
          "sun":"Son",
          "mon":"Mon",
          "tue":"Din",
          "wed":"Mit",
          "thu":"Don",
          "fri":"Fri",
          "sat":"Sam",
          "choose":"Wählen Sie ein Event",
          "createnew":"Neu erstellen",
          "savechanges":"Änderungen speichern",
          "timefree":"uhr verfügbar"
        },
        "nav":{
            "logout":"abmelden",
            "signup":"Anmelden",
            "forgot":"vergessen?",
            "login":"Einloggen",
            "goal":"Ziel / Über uns",
            "contact":"Kontaktieren",
            "ecal":"Veranstaltungskalender",
            "password":"Passwort",
        },
        "event_form":{
            "name":"Event Name",
            "des":"Beschreibung",
            "add":"Zusätzliche Informationen (kurz halten)",
            "host":"Gastorganisation",
            "price":"Preis (standardmäßig kostenlos)",
            "linkto":"Link zu einer externen Site (optional)",
            "linkdes":"Beschreibung, wohin der Link führt",
            "post":"Post-Event"
        },
        "org_info":{
            "member":"Sie sind Mitglied von",
            "join":"Möchten Sie Mitglied werden?",
            "joinit":"Beitrittsanfrage"
        },
        "profile":{
            "pro":"Profil",
            "org":"Organisationen",
            "eve":"Eventmanager",
            "email":"Send Emails",
            "upload":"Profilbild hochladen",
            "del":"Profilbild löschen",
            "save":"Änderungen speichern",
            "noorg":"Ist kein Teil einer Organisation",
            "crenew":"Erstellen Sie eine neue Organisation",
            "memof":"Sie sind Mitglied von:",
            "leave":"Verlassen",
            "request":"Beitrittsanfragen",
            "app":"Genehmigen",
            "dec":"ablehnen",
            "nonew":"Es liegen keine neuen Anfragen vor.",
            "presof":"Sie sind der Präsident von",
            "makead":"Machen Sie Admin",
            "kick":"Aus dem Club entfernen",
            "demote":"Degradieren",
            "visitclub":"Besuchen Sie die Clubseite",
            "addev":"Event hinzufügen",
            "edit":"Bearbeiten",
            "delete":"Löschen",
            "nameof":"Name der Organisation",
            "orgdes":"Beschreibung Ihrer Organisation",
            "disimg":"Bild anzeigen",
            "orglink":"Link zur Website der Organisation (optional)",
            "orgwhere":"Wohin führt der Link? (optional)",
            "youpres":"Sind Sie der Präsident?",
            "yes":"ya",
            "no":"nein",
            "sub":"Absenden",
            "confirm":"Bestätigen",
            "cancel":"Abbrechen"
        }
    }
 }
